name: Build
on: 
  push:
    branches:
      - "dev"

jobs:
  build:
    strategy:
      matrix:
        sys:
          - { os: windows, shell: 'msys2 {0}' }
          - { os: ubuntu,  shell: bash  }
          - { os: macos,   shell: bash  }
        wireshark:
          - v4.4.0

    runs-on: ${{ matrix.sys.os }}-latest

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - name: Checkout Wireshark
      uses: actions/checkout@v4
      with:
        repository: wireshark/wireshark
        ref: ${{ matrix.wireshark }}
        path: wireshark
        fetch-depth: 0

    - name: Checkout CatSniffer Plugin
      uses: actions/checkout@v4
      with:
        path: wireshark/plugins/epan/catsniffer
        fetch-depth: 0
    
    - name: Keep the folder catsniffer (Unix)
      if: matrix.sys.os != 'windows'
      run: |
        cd wireshark/plugins/epan/catsniffer
        git sparse-checkout init --cone
        git sparse-checkout set catsniffer
        git checkout
        mv catsniffer/* .
        rm -r catsniffer
    
    - name: Keep the folder catsniffer (Windows)
      if: matrix.sys.os == 'windows'
      run: |
        cd wireshark/plugins/epan/catsniffer
        git sparse-checkout init --cone
        git sparse-checkout set catsniffer
        git checkout
        robocopy catsniffer . /E /MOVE
        rmdir /S /Q catsniffer
    
    - name: Checkout CatSniffer SX1262 Plugin
      uses: actions/checkout@v4
      with:
        path: wireshark/plugins/epan/catsniffersx1262
        fetch-depth: 0
    
    - name: Keep the folder catsniffersx1262 (Unix)
      if: matrix.sys.os != 'windows'
      run: |
        cd wireshark/plugins/epan/catsniffersx1262
        git sparse-checkout init --cone
        git sparse-checkout set catsniffersx1262
        git checkout
        mv catsniffersx1262/* .
        rm -r catsniffersx1262
      
    - name: Keep the folder catsniffersx1262 (Windows)
      if: matrix.sys.os == 'windows'
      run: |
        cd wireshark/plugins/epan/catsniffersx1262
        git sparse-checkout init --cone
        git sparse-checkout set catsniffersx1262
        git checkout
        robocopy catsniffersx1262 . /E /MOVE
        rmdir /S /Q catsniffersx1262

    - name: Install dependencies (Ubuntu)
      if: matrix.sys.os == 'ubuntu'
      run: sudo wireshark/tools/debian-setup.sh --install-all python3-pip -y

    - name: Install dependencies (Mac OS)
      if: matrix.sys.os == 'macos'
      run: wireshark/tools/macos-setup-brew.sh --install-optional --install-doc-deps --install-dmg-deps --install-test-deps
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Install MSYS2 (Windows)
      if: matrix.sys.os == 'windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: base-devel

    - name: Install dependencies (Windows)
      if: matrix.sys.os == 'windows'
      run: wireshark/tools/msys2-setup.sh --install-all --noconfirm

    - name: Configure
      run: cmake -B build -S wireshark -G Ninja -DCUSTOM_PLUGIN_SRC_DIR=plugins/epan/catsniffer;plugins/epan/catsniffersx1262 -DCMAKE_INSTALL_PREFIX=/

    - name: Build
      run: |
        cmake --build build --target catsniffer
        cmake --build build --target catsniffersx1262

    - name: Install
      env:
        DESTDIR: ${{ github.workspace }}/dist
      run: |
        cmake --build build --target plugins/epan/catsniffer/install
        cmake --build build --target plugins/epan/catsniffersx1262/install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.wireshark }}_${{ matrix.sys.os }}
        path: dist/
